# Generated by Django 4.2.7 on 2023-11-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('profile_path', models.TextField(null=True)),
                ('movies', models.ManyToManyField(blank=True, related_name='actors', to='movies.movie')),
            ],
        ),
    ]
