# Generated by Django 4.2.7 on 2023-11-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='known_for_department',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
