# Generated by Django 4.2.7 on 2023-11-24 02:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Username must contain only letters and numbers.', regex='^[a-zA-Z0-9]*$')]),
        ),
    ]
